---
# tasks file for role-podman_env_setup
- name: Ensure podman is installedd
  ansible.builtin.apt:
    name:
      - podman
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Ensure podman user exists
  ansible.builtin.user:
    name: "{{ podman_user }}"
    comment: "Podman user"
    create_home: true
    password: "!"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Get home directory of podman user
  ansible.builtin.getent:
    database: passwd
    key: "{{ podman_user }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set home directory var for deploy user
  ansible.builtin.set_fact:
    podman_user_home: "{{ getent_passwd[podman_user][4] }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure podman user registry config directory
  ansible.builtin.file:
    path: "{{ podman_user_home }}/.config/containers"
    state: directory
    mode: "0750"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: "{{ podman_user }}"

- name: Setup registries config file
  ansible.builtin.copy:
    src: "/etc/containers/registries.conf"
    dest: "{{ podman_user_home }}/.config/containers"
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "0750"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Add docker as a registry
  ansible.builtin.lineinfile:
    dest: "{{ podman_user_home }}/.config/containers/registries.conf"
    line: 'unqualified-search-registries = ["docker.io"]'
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "0750"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Enable containers to run after logout
  ansible.builtin.command: /usr/bin/loginctl enable-linger {{ podman_user }}
  creates: "/var/lib/systemd/linger/{{ podman_user }}"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Allow podman containers use of privileged ports below 1024
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: "80"
    state: present
    sysctl_set: true
    reload: true
    sysctl_file: "/etc/sysctl.d/podman-privileged-ports.conf"
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root
